// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-2FLInysksPVe68BjL7wDlpzseD_lg0',
    appId: '1:260933802027:web:759c01b7cb83c04001326e',
    messagingSenderId: '260933802027',
    projectId: 'fluttereminder',
    authDomain: 'fluttereminder.firebaseapp.com',
    storageBucket: 'fluttereminder.appspot.com',
    measurementId: 'G-V601FNYKL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB20DNP9Pl6ZBchVF-RkA0SCM6Se5yJggk',
    appId: '1:260933802027:android:1975973596b6f9f101326e',
    messagingSenderId: '260933802027',
    projectId: 'fluttereminder',
    storageBucket: 'fluttereminder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKh-4mLV4fgnNXUFJoiJe7rSqKbQ5Gig',
    appId: '1:260933802027:ios:4de49a65f272537b01326e',
    messagingSenderId: '260933802027',
    projectId: 'fluttereminder',
    storageBucket: 'fluttereminder.appspot.com',
    iosBundleId: 'com.example.reminderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKh-4mLV4fgnNXUFJoiJe7rSqKbQ5Gig',
    appId: '1:260933802027:ios:4de49a65f272537b01326e',
    messagingSenderId: '260933802027',
    projectId: 'fluttereminder',
    storageBucket: 'fluttereminder.appspot.com',
    iosBundleId: 'com.example.reminderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-2FLInysksPVe68BjL7wDlpzseD_lg0',
    appId: '1:260933802027:web:c2fb0e2e840391d401326e',
    messagingSenderId: '260933802027',
    projectId: 'fluttereminder',
    authDomain: 'fluttereminder.firebaseapp.com',
    storageBucket: 'fluttereminder.appspot.com',
    measurementId: 'G-MPT371P2X8',
  );
}
